#!/bin/bash
# 1. Update OS dan instal web server/bahasa pemrograman (PHP/Node/dll)
dnf update -y
dnf install -y httpd php php-mysqli

# 2. Download kode aplikasi Anda (misal dari S3 atau GitHub)
# wget https://s3.amazonaws.com/bucket-anda/aplikasi.zip
# unzip aplikasi.zip -d /var/www/html/

# 3. Ambil kredensial dari AWS SSM (Aman, tidak ada teks password di sini)
REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
DB_HOST=$(aws ssm get-parameter --name "/app/db/endpoint" --region $REGION --query "Parameter.Value" --output text)
DB_USER=$(aws ssm get-parameter --name "/app/db/user" --region $REGION --query "Parameter.Value" --output text)
DB_PASS=$(aws ssm get-parameter --name "/app/db/password" --region $REGION --with-decryption --query "Parameter.Value" --output text)

# 4. Suntikkan ke file konfigurasi aplikasi (Misal: .env atau wp-config.php)
cat <<EOF > /var/www/html/.env
DATABASE_HOST=$DB_HOST
DATABASE_USER=$DB_USER
DATABASE_PASSWORD=$DB_PASS
EOF

# 5. Nyalakan Web Server
systemctl start httpd
systemctl enable httpd
